### ISSUE TITLE
gitignore问题

### ISSUE THREAD

**Issue by lujiajing1126** [STU-Fudan/fec#1]
bower-components不应该上传

**Comment by jackyyf** [comment]
我猜戍爷两个branch是同一个意思（让戍爷把master branch删掉就好了，留个gh-pages

**Comment by lujiajing1126** [comment]
额晕，gh-pages应该是编译了的版本
bower插在html里面识别之后编译。。
不过也不是不行感觉怪怪的-/-

**Comment by shuding** [comment]
（只是不想搞两个 branch，master 已删。
